name: script hola

on:
  push:
    branches:
      - main
      
jobs:
  runs-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout del c√≥digo
      uses: actions/checkout@v5
      
    - name: Permisos
      uses: chmod +x src/hola.sh
      
    - name: ejecucion script
      uses: ./src/hola.sh
     